adds advances in configurator
AnnieScigliano/Proyecto-Incubadora pull request #96
Opened 2024-01-25 17:34 UTC by JereC4str0

2024-03-05 19:52 UTC, javierbrk requested changes
buscar los numeros que empiecen con 36 y verificar que tengan 5 ceros ... 3600000 el perido por defecto es una hora o sea 3600 segundos o 3600 * 1000 ms

2024-03-05 19:52 UTC, javierbrk commented on src/app/configurator.lua
> +    '{"rotation_duration":5000,"rotation_period":360000,"min_temperature":37.3,"max_temperature":37.8,"ssid":"incubator","passwd":"1234554321"}')
buscar los numeros que empiecen con 36 y verificar que tengan 5 ceros ... 3600000 el perido por defecto es una hora o sea 3600 segundos o 3600 * 1000 ms

2024-03-06 17:46 UTC, JereC4str0 commented on src/app/configurator.lua
> +    '{"rotation_duration":5000,"rotation_period":360000,"min_temperature":37.3,"max_temperature":37.8,"ssid":"incubator","passwd":"1234554321"}')
recien veo esto, ahora lo modifico

2024-03-12 18:32 UTC, JereC4str0 commented on src/app/configurator.lua
> +  if file ~= nil then
https://github.com/JereC4str0/Proyecto-Incubadora/blob/3f2583c9aa6e732aafb3d29c23e8aa8bfeb49338/src/app/configurator.lua#L63

2024-03-12 18:37 UTC, JereC4str0 commented on src/app/configurator.lua
> +function configurator.change_config_file(config_table)
creo que lo resolvimos en la reunion anterior, quedó algo [asi](https://github.com/JereC4str0/Proyecto-Incubadora/blob/3f2583c9aa6e732aafb3d29c23e8aa8bfeb49338/src/app/restapi.lua#L16)

2024-03-14 12:01 UTC, javierbrk requested changes
El archivo de testing debe existir. El contenido de testing no debe estar en el README. Eso fue echo a propósito para no tener un archivo enorme con muchas cosas. 
Este pull request agrega ademas archivos de tu ordenador que no deben estar como tdd.. .vscode... settings.json
El archivo tables.lua tiene un nombre muy genérico, debería llevar un nombre que alguien que lo vea pueda imaginar que es lo que tiene. De que son las tablas que tiene ese archivo ? 
todo lo que no tenga que ver con config deberia estar afuera de este commit

2024-03-20 18:39 UTC, javierbrk approved these changes

2024-03-20 22:36 UTC, merged